import assert from 'node:assert/strict';
import { HitReaction, notifyVisualHit, observeVisualHits } from '../../src/entities/hit-reaction';
const reaction = new HitReaction();
const initial = { ...reaction.advance(16) };
assert.deepEqual(initial, { x: 0, y: 0, scaleX: 1, scaleY: 1 });
const stop = observeVisualHits('enemy', reaction.receive);
notifyVisualHit('other', 1, 0);
assert.deepEqual({ ...reaction.advance(16) }, initial, 'unrelated targets never flinch');
notifyVisualHit('enemy', 20, 0);
const early = { ...reaction.advance(20) };
assert.ok(early.x > 2 && early.x < 4 && early.scaleX < .9 && early.scaleY > 1);
assert.equal(early.y, 0);
const late = { ...reaction.advance(130) };
assert.ok(late.x < 0, 'small damped return passes through the original pose');
assert.deepEqual({ ...reaction.advance(100) }, initial, 'exact baseline restored');
notifyVisualHit('enemy', 0, -10);
assert.ok(reaction.advance(20).y < -2, 'force direction retained');
reaction.advance(300); stop(); notifyVisualHit('enemy', 20, 0);
assert.deepEqual({ ...reaction.advance(20) }, initial, 'destroyed visual unsubscribed');
console.log('hit-reaction PASS: real-target routing, force direction, bounded compression, rebound, baseline and cleanup');
