/** Export the exact same deterministic surface used by the playable viewer. */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { generateWorldSample } from '../../src/generation/world-study/layout';
import { renderWorldSurface } from '../../src/generation/world-study/surface';
import { WORLD_PROFILES } from '../../src/generation/world-study/profiles';
import { worldSupportAt } from '../../src/generation/world-study/support';
import { groundMaterialHighlights } from '../../src/generation/world-study/material-response';
import type { WorldTopologyId } from '../../src/generation/world-study/types';

const seed = process.argv[2] === undefined ? 70421 : Number(process.argv[2]);
const directory = path.resolve(process.argv[3] ?? 'docs/qa/artifacts/rift-world-study');
await mkdir(directory, { recursive: true });
const records = [];
for (const profile of WORLD_PROFILES) for (const topology of ['loops', 'channels'] as const satisfies readonly WorldTopologyId[]) {
  const start = performance.now();
  const sample = generateWorldSample(profile.id, topology, seed);
  const surface = renderWorldSurface(sample);
  if (surface.rgba.length !== surface.width * surface.height * 4) throw new Error('Invalid renderer output dimensions');
  let voidPixels = 0;
  for (let y = 0; y < surface.height; y++) for (let x = 0; x < surface.width; x++) {
    if (worldSupportAt(sample, x, y)) continue;
    const offset = (y * surface.width + x) * 4;
    if (surface.rgba[offset] || surface.rgba[offset + 1] || surface.rgba[offset + 2] || surface.rgba[offset + 3] !== 255) {
      throw new Error(`Missing space acquired a visible surface at ${profile.id} ${x},${y}`);
    }
    voidPixels++;
  }
  if (Object.values(profile.palette).every(color => (color >> 16 & 255) === (color >> 8 & 255) && (color >> 8 & 255) === (color & 255))) {
    for (let offset = 0; offset < surface.rgba.length; offset += 4) {
      if (surface.rgba[offset] !== surface.rgba[offset + 1] || surface.rgba[offset + 1] !== surface.rgba[offset + 2]) {
        throw new Error(`Achromatic surface has colored pixels at offset ${offset}`);
      }
    }
  }
  const file = `${profile.id}-${topology}-terrain.png`;
  const highlights = groundMaterialHighlights(sample);
  if (profile.surface.substrate === 'strata' && profile.surface.coating === 'strata' && highlights.length !== 0) {
    throw new Error(`${profile.id}: reflection samples disagree with material response`);
  }
  for (const highlight of highlights) for (let dy = 0; dy < highlight.height; dy++) for (let dx = 0; dx < highlight.width; dx++) {
    const x = highlight.x + dx, y = highlight.y + dy;
    if (!worldSupportAt(sample, x, y)) throw new Error(`${profile.id}: reflection spills into missing space at ${x},${y}`);
  }
  await sharp(surface.rgba, { raw: { width: surface.width, height: surface.height, channels: 4 } }).png().toFile(path.join(directory, file));
  records.push({ world: profile.id, topology, seed, file, width: surface.width, height: surface.height,
    renderAndCheckMs: Math.round(performance.now() - start), formations: sample.formations.length, voidPixels, reflectionSamples: highlights.length });
  console.log(JSON.stringify(records[records.length - 1]));
}
await writeFile(path.join(directory, 'terrain-manifest.json'), JSON.stringify({ scope: 'Raw game surfaces, generated by the playable viewer renderer.', records }, null, 2));
