/** Inventory uses the accepted report's shared scene material and typography. */
const STYLE_ID = 'inventory-panel-styles';
const CSS = `
.inventory-detail-column > .inventory-actions{flex:none;margin-top:0;padding:7px 0 0 18px;border-left:1px solid #263525;min-height:26px;gap:5px 12px}
.inventory-detail-column > .inventory-actions:empty{display:none}
.inventory-detail-meta{overflow-wrap:normal;word-break:keep-all}
.inventory-wrap{box-sizing:border-box;display:flex;flex-direction:column;gap:12px;font:11px/18px var(--ui-font);color:#9eaa98;pointer-events:auto;outline:none}
#inventory-panel.game-panel{left:330px;top:102px;width:598px;height:490px;padding:0;z-index:1100}
#inventory-panel.is-prepare{left:282px;top:74px;width:646px;height:524px}
.inventory-catalog{position:relative;min-height:0;flex:1;width:100%;height:100%}
.inventory-wrap *{box-sizing:border-box}.inventory-wrap [hidden]{display:none!important}.inventory-wrap button,.inventory-wrap select{font:inherit;color:inherit;border-radius:0}.inventory-wrap button{background:none;border:0;padding:0;cursor:pointer;text-align:left}.inventory-wrap button:disabled{color:#657260;cursor:default}.inventory-wrap button:focus-visible,.inventory-wrap select:focus-visible{outline:1px solid #748367;outline-offset:3px}
.inventory-header{display:flex;align-items:baseline;gap:16px;flex:none;margin-bottom:8px}.inventory-title{font:16px/24px var(--ui-font);letter-spacing:1px;color:#b2b5a6;margin:0}.inventory-context{font-size:10px;color:#75816f}.inventory-close{margin-left:auto!important;font-size:10px!important;color:#82907b!important;white-space:nowrap}.inventory-weight{margin-left:auto;white-space:nowrap;font-size:10px;position:relative}.inventory-weight strong{font:11px/18px var(--ui-mono);font-weight:400;margin-left:8px;color:#a7b19b}.inventory-weight.is-over strong{color:#b69671}.inventory-survival{display:block;font-size:9px;color:#7e8b72}.inventory-weight+.inventory-close{margin-left:0!important}
.inventory-equipment{height:118px;display:flex;align-items:center;gap:13px;flex:none;margin:0 0 5px}.inventory-player-portrait{width:68px;height:106px;object-fit:contain;image-rendering:pixelated;opacity:.75;margin-right:0;filter:drop-shadow(0 4px 3px #030806)}.inventory-slot{display:flex;flex-direction:column;align-items:center;gap:2px;min-width:0;flex:1;align-self:stretch;justify-content:center;position:relative;border-bottom:1px solid #263325!important}.inventory-slot[data-slot-id=weapon]{flex:1.45}.inventory-slot[data-slot-id=weapon]{flex:0 0 110px;margin-right:16px}.inventory-slot[data-slot-id=weapon]::before{content:'';position:absolute;left:-29px;top:59px;width:45px;height:9px;border-left:1px solid #3a4833;border-bottom:1px solid #3a4833;pointer-events:none}.inventory-slot-icon{display:block;width:42px;height:42px}.inventory-slot[data-slot-id=weapon] .inventory-slot-icon{width:62px;height:62px}.inventory-slot-label{font:10px/14px var(--ui-mono);color:#a5af93}.inventory-slot-name{font-size:10px;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.inventory-slot-uses{font-size:9px;color:#748568}.inventory-slot.is-looking{border-bottom-color:#9ba78d!important}.inventory-slot.is-locked{opacity:.5}
.inventory-filters{display:flex;align-items:center;gap:20px;flex:none;height:24px}.inventory-filter{font-size:11px!important;color:#788773!important}.inventory-filter.is-current{color:#bdc2ac!important}.inventory-sort{margin-left:auto;border:0;background:#101810;font-size:10px!important;max-width:92px}.inventory-body{display:grid;grid-template-columns:minmax(0,1fr) 186px;gap:22px;flex:1;min-height:0;overflow:hidden}#inventory-panel > .inventory-body{flex:1 1 0;min-height:0}.inventory-list-column{display:flex;flex-direction:column;min-width:0;min-height:0}.inventory-column-heading{display:flex;justify-content:space-between;color:#72836b;font-size:10px;min-height:24px;flex:none}.inventory-column-heading strong{font-weight:400;font-size:10px}.inventory-list{overflow:auto;flex:1;min-height:0;scrollbar-width:thin;scrollbar-color:#3c503b transparent;overscroll-behavior:contain;padding-right:4px}.inventory-item{display:grid;grid-template-columns:42px minmax(0,1fr);gap:10px;width:100%;height:52px;align-items:center;padding:4px 0!important}.is-rift .inventory-item{grid-template-columns:38px minmax(0,1fr) 30px}.inventory-item-image{width:40px;height:40px;display:block;opacity:.85}.inventory-item-copy{min-width:0;display:flex;flex-direction:column;gap:2px}.inventory-item-name{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#9da991}.inventory-item-caption{font-size:9px;color:#657b62;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.inventory-item-weight{font:10px/16px var(--ui-mono);text-align:right;color:#8a997e}.inventory-item.is-looking .inventory-item-name{color:#c0c6ac}.inventory-item.is-looking .inventory-item-image{filter:brightness(1.15)}.inventory-item.is-picked .inventory-item-name::before{content:'✓ ';color:#b2b79a}.inventory-position{font-size:9px;color:#63775b;min-height:18px;flex:none}.inventory-empty{padding:20px 0;font-size:11px;color:#748367}
.inventory-detail-column{display:flex;flex-direction:column;min-height:0;overflow:hidden}.inventory-detail-hint{flex:0 0 15px;font-size:9px;line-height:15px;text-align:right;color:#78866d}.inventory-detail{flex:1 1 0;min-height:0;overflow:auto;scrollbar-width:thin;scrollbar-color:#3c503b transparent;border-left:1px solid #263525;padding-left:18px}.inventory-art{height:74px;width:88px;margin:0 auto 9px}.inventory-wrap img,.inventory-wrap svg{width:100%;height:100%;object-fit:contain;image-rendering:pixelated}.inventory-wrap .inventory-player-portrait{width:68px;height:106px}.inventory-detail h3{font-size:12px;line-height:18px;font-weight:400;margin:0 0 5px;color:#bcc0ab}.inventory-detail-meta{font-size:9px;color:#74836b}.inventory-detail p{font-size:10px;line-height:17px;color:#84927a;margin:7px 0}.inventory-stat{display:flex;justify-content:space-between;gap:7px;font-size:10px;line-height:19px}.inventory-stat span{color:#718468}.inventory-stat strong{font-weight:400;text-align:right;color:#a8b195}.inventory-explanation{margin-top:10px;font-size:10px;line-height:17px;color:#84927a}.inventory-explanation summary{cursor:pointer;color:#a5b291}.inventory-explanation summary:focus-visible{outline:1px solid #748367;outline-offset:3px}.inventory-detail-uses{margin-top:4px}.inventory-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px}.inventory-action{font-size:10px!important;padding:4px 0!important;border-bottom:1px solid #435438!important;color:#a5b291!important}.inventory-action:disabled{color:#566c50!important}.inventory-discard{position:relative;color:#9b8d70!important;overflow:hidden}.inventory-discard::after{content:'';position:absolute;left:0;right:0;bottom:0;height:2px;background:#b19774;transform:scaleX(0);transform-origin:left;pointer-events:none}.inventory-discard.is-holding::after{transform:scaleX(1);transition:transform var(--discard-hold-duration) linear}
.inventory-bottom{flex:none;margin-top:4px;min-height:47px}.inventory-message{font-size:10px;line-height:16px;color:#8a987e;min-height:16px;margin-bottom:6px}.inventory-bottom-row{display:flex;align-items:center;gap:15px}.inventory-key-help{font-size:9px;color:#677e5e;flex:1}.inventory-primary{font-size:11px!important;color:#b8b99e!important;border-bottom:1px solid #4c5c42!important;padding:4px 0!important;white-space:nowrap}.inventory-primary:disabled{color:#637657!important}.inventory-catalog .inventory-item{height:48px}.inventory-catalog .inventory-bottom{min-height:16px;margin-top:0}.inventory-catalog .inventory-message{margin-bottom:0}.inventory-catalog .inventory-bottom-row{display:none}.inventory-exchange-inspect{display:none;flex:none;font-size:10px;line-height:17px;max-height:54px;overflow:auto;color:#879c7f}.is-exchange .inventory-exchange-inspect{display:block}.is-exchange .inventory-body{grid-template-columns:1fr 1fr;gap:24px}.is-exchange .inventory-detail-column{display:none}.is-exchange .inventory-item{grid-template-columns:32px minmax(0,1fr) 28px;gap:7px}.is-exchange .inventory-item-image{width:30px;height:30px}.inventory-wrap.is-busy button:not(.inventory-close){pointer-events:none;opacity:.65}
`;
export function ensureInventoryPanelStyles(): void {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = CSS; document.head.appendChild(style);
}
