/** Fixed 960×640 inventory presentation. All selectors belong to this view. */
const STYLE_ID = 'inventory-panel-styles';
const CSS = `
.inventory-wrap{position:absolute;left:270px;top:28px;width:666px;height:588px;pointer-events:auto;z-index:1100;font:12px/18px "PingFang SC","Microsoft YaHei",sans-serif;color:#b7b6a9;isolation:isolate;box-sizing:border-box;padding:20px 24px 14px 28px;display:flex;flex-direction:column;gap:12px;outline:none}
.inventory-wrap::before{content:"";position:absolute;inset:0;z-index:-2;background:linear-gradient(95deg,rgba(13,17,15,.78),rgba(16,20,17,.96) 9%,rgba(12,16,14,.97) 91%,rgba(10,14,12,.82));clip-path:polygon(2% 0,98% 1%,100% 6%,99% 42%,100% 81%,98% 100%,3% 99%,0 92%,1% 56%,0 8%)}
.inventory-wrap::after{content:"";position:absolute;inset:5px 8px;pointer-events:none;z-index:-1;opacity:.2;background:repeating-linear-gradient(0deg,transparent 0 3px,rgba(120,115,87,.07) 3px 4px),repeating-linear-gradient(90deg,transparent 0 5px,rgba(150,140,99,.065) 5px 6px);border-top:1px solid #575a47;border-bottom:1px solid #30392c}
.inventory-wrap *{box-sizing:border-box}.inventory-wrap button,.inventory-wrap select{font:inherit;color:inherit;border-radius:0}.inventory-wrap button{cursor:pointer;background:none;border:0;padding:0;margin:0}.inventory-wrap button:disabled{cursor:default;color:#636e60}.inventory-wrap button:focus-visible,.inventory-wrap select:focus-visible{outline:1px solid #9b9f7e;outline-offset:3px}.inventory-wrap [hidden]{display:none!important}
.inventory-header{height:32px;display:flex;align-items:baseline;gap:16px;flex:0 0 auto}.inventory-title{margin:0;font-size:18px;font-weight:400;letter-spacing:2px;color:#c3c0b0}.inventory-context{font-size:10px;color:#859080}.inventory-weight{position:relative;margin-left:auto;font-size:11px;white-space:nowrap}.inventory-weight strong{font-size:14px;font-weight:400;color:#c1baa3;margin-left:9px;font-variant-numeric:tabular-nums}.inventory-weight.is-over strong{color:#bf916a}.inventory-survival{position:absolute;right:0;top:18px;font-size:10px;line-height:13px;color:#899682}.inventory-close{margin-left:8px!important;padding:2px 5px!important;font-size:11px!important;color:#92998a!important}
.inventory-equipment{height:82px;flex:0 0 auto;display:flex;gap:10px;align-items:stretch;position:relative;padding:8px 8px 4px 0}.inventory-equipment::before{content:"";position:absolute;left:0;right:0;top:19px;height:37px;border-top:1px solid #504b36;border-bottom:2px solid #171c14;background:repeating-linear-gradient(90deg,#302f22 0 3px,#292b20 3px 5px);opacity:.64}.inventory-slot{position:relative;flex:0 0 54px;min-width:0;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;padding:2px 3px!important;gap:3px;color:#8e9584!important}.inventory-slot:first-child{flex:1;align-items:flex-start;padding-left:18px!important}.inventory-slot::before,.inventory-slot:first-child::after{content:"";position:absolute;width:7px;top:5px;bottom:21px;left:2px;background:#494332;border-left:1px solid #696044;border-right:2px solid #24291e}.inventory-slot:first-child::after{left:auto;right:22px}.inventory-slot-icon{height:40px;width:40px;display:flex;align-items:center;justify-content:center;filter:brightness(.86)}.inventory-slot:first-child .inventory-slot-icon{position:absolute;width:172px;height:47px;top:2px;left:12px}.inventory-slot:first-child .inventory-slot-icon img{width:96px;height:96px;transform:rotate(-90deg);flex:none}.inventory-slot:first-child .inventory-slot-icon svg{transform:rotate(-82deg);height:125px;width:60px}.inventory-slot-label{font-size:10px;line-height:16px;z-index:1}.inventory-slot:first-child .inventory-slot-label{max-width:210px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.inventory-slot.is-looking .inventory-slot-label{color:#c7c6b3}.inventory-slot.is-locked{opacity:.45}.inventory-slot svg,.inventory-item-image svg,.inventory-art svg{width:100%;height:100%;shape-rendering:crispEdges}.inventory-slot img,.inventory-item-image img,.inventory-art img{width:100%;height:100%;object-fit:contain;image-rendering:pixelated}
.inventory-filters{height:25px;display:flex;gap:15px;align-items:center;flex:0 0 auto;border-bottom:1px solid #30392b;padding-bottom:7px}.inventory-filter{font-size:11px!important;color:#828e7e!important;position:relative}.inventory-filter.is-current{color:#c0c0ac!important}.inventory-filter.is-current::after{content:"";position:absolute;left:0;bottom:-8px;width:18px;height:2px;background:#aaa88a}.inventory-sort{margin-left:auto;background:#151b16;border:0;font-size:10px!important;max-width:86px;padding:2px}.inventory-carried-toggle{font-size:10px!important;color:#899382!important}.inventory-carried-toggle[aria-pressed=true]{color:#c3c4b0!important}
.inventory-body{display:grid;grid-template-columns:minmax(0,1fr) 202px;gap:22px;min-height:0;flex:1;position:relative}.inventory-list-column{display:flex;flex-direction:column;min-width:0;min-height:0}.inventory-column-heading{font-size:11px;color:#8d9988;display:flex;justify-content:space-between;min-height:24px;flex:0 0 auto}.inventory-column-heading strong{font:10px/18px inherit;font-weight:400;color:#a8af99}.inventory-list{overflow-y:auto;overflow-x:hidden;min-height:0;flex:1;scrollbar-width:thin;scrollbar-color:#59604a #151c15;overscroll-behavior:contain;padding:2px 4px 2px 0}.inventory-list::-webkit-scrollbar{width:3px}.inventory-list::-webkit-scrollbar-thumb{background:#59604a}.inventory-item{display:grid;grid-template-columns:44px minmax(0,1fr) 42px;align-items:center;gap:8px;width:100%;height:48px;text-align:left;padding:4px 4px 4px 8px!important;position:relative;border-bottom:1px solid rgba(90,103,77,.14)!important}.inventory-item.is-looking{background:rgba(123,139,99,.075)}.inventory-item.is-looking::before{content:"";position:absolute;left:0;top:18px;width:3px;height:11px;background:#a4aa89;clip-path:polygon(0 0,100% 18%,85% 100%,0 81%)}.inventory-item.is-picked::after{content:"";position:absolute;left:36px;top:5px;width:7px;height:12px;background:#ada886;clip-path:polygon(0 0,100% 0,100% 100%,49% 72%,0 100%)}.inventory-item-image{width:40px;height:38px;display:block;opacity:.9}.inventory-item-copy{min-width:0;display:flex;flex-direction:column;gap:1px}.inventory-item-name{font-size:12px;line-height:17px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#b1b5a1}.inventory-item-caption{font-size:10px;line-height:15px;color:#7d8d7c;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.inventory-item-weight{font-size:11px;text-align:right;color:#9fa48e;font-variant-numeric:tabular-nums}.inventory-position{font-size:10px;min-height:18px;color:#798775;flex:0 0 auto;padding-top:3px}.inventory-empty{padding:24px 8px;color:#7b8c78;font-size:11px}
.inventory-detail{min-height:0;overflow-y:auto;scrollbar-width:thin;scrollbar-color:#59604a #151c15;border-left:1px solid #35402e;padding-left:20px}.inventory-art{height:96px;max-width:150px;margin:0 auto 10px;position:relative}.inventory-art.is-weapon svg{transform:rotate(14deg)}.inventory-preview{color:#bab497!important;font-size:10px!important;line-height:16px!important}.inventory-detail h3{font-size:13px;font-weight:400;line-height:19px;margin:0 0 5px;color:#c0c0ad}.inventory-detail p{font-size:11px;line-height:18px;color:#9aa68e;margin:6px 0 10px;white-space:pre-line}.inventory-detail-meta{font-size:10px;color:#86927d}.inventory-stat{display:flex;justify-content:space-between;gap:8px;font-size:11px;line-height:20px}.inventory-stat span{color:#88967e}.inventory-stat strong{font-weight:400;color:#b5b7a0;text-align:right}.inventory-actions{display:flex;flex-wrap:wrap;gap:5px 12px;margin-top:12px;padding-top:9px;border-top:1px solid #36402d}.inventory-action{padding:3px 1px!important;font-size:11px!important;color:#b8b69d!important;border-bottom:1px solid #686b4e!important}.inventory-discard{position:relative;color:#ab977e!important;overflow:hidden}.inventory-discard::after{content:"";position:absolute;left:0;right:0;bottom:0;height:2px;background:#b19774;transform:scaleX(0);transform-origin:left;pointer-events:none}.inventory-discard.is-holding::after{transform:scaleX(1);transition:transform var(--discard-hold-duration) linear}.inventory-action:disabled{border-color:#303c2c!important;color:#697761!important}.inventory-locked-note{font-size:10px!important;color:#889680!important}
.inventory-bottom{flex:0 0 auto;min-height:66px;border-top:1px solid #414936;padding-top:8px}.inventory-message{font-size:11px;min-height:20px;color:#aaa78d;margin-bottom:5px;white-space:pre-line}.inventory-bottom-row{display:flex;align-items:center;gap:14px;min-height:26px}.inventory-key-help{font-size:10px;line-height:16px;color:#7d8c74;flex:1}.inventory-primary{font-size:12px!important;padding:5px 8px!important;border-bottom:1px solid #85856b!important;color:#c8c3aa!important;white-space:nowrap}.inventory-primary:disabled{border-color:#3e4834!important;color:#7b816c!important}.inventory-primary kbd{font:10px/16px inherit;padding-right:7px;color:#999f85}.inventory-wrap.is-exchange .inventory-body{grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:18px}.inventory-wrap.is-exchange .inventory-detail{display:none}.inventory-wrap.is-exchange .inventory-equipment{height:60px}.inventory-wrap.is-exchange .inventory-slot-label{font-size:9px}.inventory-wrap.is-exchange .inventory-slot:first-child .inventory-slot-icon{height:34px}.inventory-wrap.is-exchange .inventory-slot:first-child .inventory-slot-icon svg{height:106px}.inventory-wrap.is-exchange .inventory-item{grid-template-columns:36px minmax(0,1fr) 35px;gap:6px}.inventory-wrap.is-exchange .inventory-item-image{width:32px}.inventory-exchange-inspect{display:none;flex:0 0 auto;min-height:30px;max-height:58px;overflow-y:auto;font-size:11px;line-height:18px;color:#a2ac93;padding:0 4px;border-bottom:1px solid #30392b}.inventory-wrap.is-exchange .inventory-exchange-inspect{display:block}.inventory-wrap.is-busy button:not(.inventory-close){pointer-events:none;opacity:.65}
@media(prefers-reduced-motion:no-preference){.inventory-wrap{animation:inventory-unroll .16s ease-out}.inventory-item-image{transition:filter .08s}.inventory-item.is-looking .inventory-item-image{filter:brightness(1.12)}@keyframes inventory-unroll{from{opacity:0;transform:translateX(8px)}to{opacity:1;transform:translateX(0)}}
`;
export function ensureInventoryPanelStyles(): void {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement('style');
  style.id = STYLE_ID;
  style.textContent = CSS;
  document.head.appendChild(style);
}
