/**
 * CSV → TypeScript codegen.
 *
 * Reads data/*.csv and generates src/generated/*.ts with typed constants.
 * No external dependencies — uses built-in fs and simple comma-split parsing
 * (the CSV data uses Chinese punctuation, never ASCII commas inside fields).
 *
 * Usage: node tools/csv-codegen/generate.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const DATA_DIR = resolve(ROOT, 'data');
const OUT_DIR = resolve(ROOT, 'src/generated');

// Ensure output directory exists
mkdirSync(OUT_DIR, { recursive: true });

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Read a CSV file, strip BOM, return rows as string[][].
 * First row is the header.
 */
function readCsv(filename) {
  let raw = readFileSync(resolve(DATA_DIR, filename), 'utf-8');
  // Strip UTF-8 BOM (EF BB BF appears as ﻿ in the decoded string)
  if (raw.charCodeAt(0) === 0xfeff) {
    raw = raw.slice(1);
  }
  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);
  const header = lines[0].split(',');
  const rows = lines.slice(1).map((line) => line.split(','));
  return { header, rows };
}

/** Convert snake_case to camelCase. */
function toCamel(s) {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** Escape a string for use inside a TS template literal or single-quoted string. */
function escapeStr(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

// ---------------------------------------------------------------------------
// Generate contaminant-data.ts
// ---------------------------------------------------------------------------

function generateContaminants() {
  const { header, rows } = readCsv('contaminants.csv');

  // Map header indices
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => ({
    id: cols[idx.id],
    rarity: cols[idx.rarity],
    displayNameDefense: cols[idx.display_name_defense],
    descriptionDefense: cols[idx.description_defense],
    summaryDefense: cols[idx.summary_defense] ?? '',
    defenseCategory: cols[idx.defense_category],
    defenseReduction: parseFloat(cols[idx.defense_reduction]),
    defenseSideEffect: cols[idx.defense_side_effect],
    sideEffectDuration: cols[idx.side_effect_duration],
    defenseChargeMult: parseFloat(cols[idx.defense_charge_mult]),
    displayNameTool: cols[idx.display_name_tool],
    descriptionTool: cols[idx.description_tool],
    summaryTool: cols[idx.summary_tool] ?? '',
    toolType: cols[idx.tool_type],
    toolUses: parseInt(cols[idx.tool_uses], 10),
    toolRangePx: parseInt(cols[idx.tool_range_px], 10),
    toolDurationMs: parseInt(cols[idx.tool_duration_ms], 10),
    narrativeOrigin: cols[idx.narrative_origin],
  }));

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    "import type { ContaminantType, ContaminantRarity } from '@/types/game-types';",
    '',
    'export interface ContaminantDef {',
    '  id: ContaminantType;',
    '  rarity: ContaminantRarity;',
    '  displayNameDefense: string;',
    '  descriptionDefense: string;',
    '  summaryDefense: string;',
    '  defenseCategory: string;',
    '  defenseReduction: number;',
    '  defenseSideEffect: string;',
    '  sideEffectDuration: string;',
    '  defenseChargeMult: number;',
    '  displayNameTool: string;',
    '  descriptionTool: string;',
    '  summaryTool: string;',
    "  toolType: 'active' | 'passive';",
    '  toolUses: number;',
    '  toolRangePx: number;',
    '  toolDurationMs: number;',
    '  narrativeOrigin: string;',
    '}',
    '',
    'export const CONTAMINANT_DATA: Record<ContaminantType, ContaminantDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${e.id}',`);
    lines.push(`    rarity: '${e.rarity}',`);
    lines.push(`    displayNameDefense: '${escapeStr(e.displayNameDefense)}',`);
    lines.push(`    descriptionDefense: '${escapeStr(e.descriptionDefense)}',`);
    lines.push(`    summaryDefense: '${escapeStr(e.summaryDefense)}',`);
    lines.push(`    defenseCategory: '${escapeStr(e.defenseCategory)}',`);
    lines.push(`    defenseReduction: ${e.defenseReduction},`);
    lines.push(`    defenseSideEffect: '${escapeStr(e.defenseSideEffect)}',`);
    lines.push(`    sideEffectDuration: '${escapeStr(e.sideEffectDuration)}',`);
    lines.push(`    defenseChargeMult: ${e.defenseChargeMult},`);
    lines.push(`    displayNameTool: '${escapeStr(e.displayNameTool)}',`);
    lines.push(`    descriptionTool: '${escapeStr(e.descriptionTool)}',`);
    lines.push(`    summaryTool: '${escapeStr(e.summaryTool)}',`);
    lines.push(`    toolType: '${e.toolType}',`);
    lines.push(`    toolUses: ${e.toolUses},`);
    lines.push(`    toolRangePx: ${e.toolRangePx},`);
    lines.push(`    toolDurationMs: ${e.toolDurationMs},`);
    lines.push(`    narrativeOrigin: '${escapeStr(e.narrativeOrigin)}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'contaminant-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  contaminant-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Generate upgrade-data.ts
// ---------------------------------------------------------------------------

function generateUpgrades() {
  const { header, rows } = readCsv('upgrades.csv');
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => {
    const maxLevel = parseInt(cols[idx.max_level], 10);
    const costs = [];
    for (let i = 1; i <= 5; i++) {
      const val = cols[idx[`cost_${i}`]];
      if (val && val.trim() !== '') {
        costs.push(parseInt(val, 10));
      }
    }
    return {
      id: cols[idx.id],
      axis: cols[idx.axis],
      maxLevel,
      effectPerLevel: parseFloat(cols[idx.effect_per_level]),
      effectUnit: cols[idx.effect_unit],
      costs,
      description: cols[idx.description]?.trim() ?? '',
    };
  });

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    "import type { GrowthUpgradeId } from '@/types/game-types';",
    '',
    'export interface UpgradeDef {',
    '  id: GrowthUpgradeId;',
    '  axis: string;',
    '  maxLevel: number;',
    '  effectPerLevel: number;',
    '  effectUnit: string;',
    '  costs: number[];',
    '  description: string;',
    '}',
    '',
    'export const UPGRADE_DATA: Record<GrowthUpgradeId, UpgradeDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${e.id}',`);
    lines.push(`    axis: '${escapeStr(e.axis)}',`);
    lines.push(`    maxLevel: ${e.maxLevel},`);
    lines.push(`    effectPerLevel: ${e.effectPerLevel},`);
    lines.push(`    effectUnit: '${escapeStr(e.effectUnit)}',`);
    lines.push(`    costs: [${e.costs.join(', ')}],`);
    lines.push(`    description: '${escapeStr(e.description)}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'upgrade-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  upgrade-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function num(s) {
  if (s === undefined || s === null || String(s).trim() === '') return 0;
  return parseFloat(s);
}

function flag(s) {
  const v = String(s ?? '').trim().toLowerCase();
  return v === 'true' || v === '1';
}

function generateRiftFragments() {
  const { header, rows } = readCsv('rift-fragments.csv');
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => ({
    id: cols[idx.id],
    displayName: cols[idx.display_name],
    l1Key: cols[idx.l1_key],
    sourceDomain: cols[idx.source_domain],
    coverage: cols[idx.coverage],
    massGrammar: cols[idx.mass_grammar],
    join: cols[idx.join],
    surfaceMaterial: cols[idx.surface_material],
    enabled: flag(cols[idx.enabled]),
    floorBv: num(cols[idx.floor_bv]),
    floorBiasR: num(cols[idx.floor_bias_r]),
    floorBiasG: num(cols[idx.floor_bias_g]),
    floorBiasB: num(cols[idx.floor_bias_b]),
    stainKey: cols[idx.stain_key] ?? '',
    stainThreshold: num(cols[idx.stain_threshold]),
    stainStrength: num(cols[idx.stain_strength]),
    grimeAmp: num(cols[idx.grime_amp]),
    macroAmp: num(cols[idx.macro_amp]),
    scratchPer1000px2: num(cols[idx.scratch_per_1000px2]),
    fleckPer1000px2: num(cols[idx.fleck_per_1000px2]),
    scratchAngle: cols[idx.scratch_angle] ?? '',
    wallBodyKey: cols[idx.wall_body_key] ?? '',
    wallRimKey: cols[idx.wall_rim_key] ?? '',
    wallBv: num(cols[idx.wall_bv]),
    wallBiasR: num(cols[idx.wall_bias_r]),
    wallBiasG: num(cols[idx.wall_bias_g]),
    wallBiasB: num(cols[idx.wall_bias_b]),
    featureWidthTiles: num(cols[idx.feature_width_tiles]),
    featureLengthTiles: num(cols[idx.feature_length_tiles]),
    featureCountMin: num(cols[idx.feature_count_min]),
    featureCountMax: num(cols[idx.feature_count_max]),
  }));

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    '',
    'export type SourceDomain = \'mundane\' | \'virtual\' | \'alien\';',
    '',
    'export type Coverage = \'remnant\' | \'half\' | \'unnamed\';',
    '',
    'export type MassGrammar =',
    "  | 'enclosure'",
    "  | 'ridge'",
    "  | 'cluster'",
    "  | 'slab'",
    "  | 'lattice'",
    "  | 'growth';",
    '',
    "export type FragmentJoin = 'single' | 'shear';",
    '',
    "export type ScratchAngle = 'free' | 'orthogonal' | 'longitudinal' | '';",
    '',
    'export interface RiftFragmentDef {',
    '  id: string;',
    '  displayName: string;',
    '  l1Key: string;',
    '  sourceDomain: SourceDomain;',
    '  coverage: Coverage;',
    '  massGrammar: MassGrammar;',
    '  join: FragmentJoin;',
    '  surfaceMaterial: string;',
    '  enabled: boolean;',
    '  floorBv: number;',
    '  floorBiasR: number;',
    '  floorBiasG: number;',
    '  floorBiasB: number;',
    '  stainKey: string;',
    '  stainThreshold: number;',
    '  stainStrength: number;',
    '  grimeAmp: number;',
    '  macroAmp: number;',
    '  scratchPer1000px2: number;',
    '  fleckPer1000px2: number;',
    '  scratchAngle: ScratchAngle;',
    '  wallBodyKey: string;',
    '  wallRimKey: string;',
    '  wallBv: number;',
    '  wallBiasR: number;',
    '  wallBiasG: number;',
    '  wallBiasB: number;',
    '  featureWidthTiles: number;',
    '  featureLengthTiles: number;',
    '  featureCountMin: number;',
    '  featureCountMax: number;',
    '}',
    '',
    'export const RIFT_FRAGMENT_DATA: Record<string, RiftFragmentDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${escapeStr(e.id)}',`);
    lines.push(`    displayName: '${escapeStr(e.displayName)}',`);
    lines.push(`    l1Key: '${escapeStr(e.l1Key)}',`);
    lines.push(`    sourceDomain: '${escapeStr(e.sourceDomain)}',`);
    lines.push(`    coverage: '${escapeStr(e.coverage)}',`);
    lines.push(`    massGrammar: '${escapeStr(e.massGrammar)}',`);
    lines.push(`    join: '${escapeStr(e.join)}',`);
    lines.push(`    surfaceMaterial: '${escapeStr(e.surfaceMaterial)}',`);
    lines.push(`    enabled: ${e.enabled},`);
    lines.push(`    floorBv: ${e.floorBv},`);
    lines.push(`    floorBiasR: ${e.floorBiasR},`);
    lines.push(`    floorBiasG: ${e.floorBiasG},`);
    lines.push(`    floorBiasB: ${e.floorBiasB},`);
    lines.push(`    stainKey: '${escapeStr(e.stainKey)}',`);
    lines.push(`    stainThreshold: ${e.stainThreshold},`);
    lines.push(`    stainStrength: ${e.stainStrength},`);
    lines.push(`    grimeAmp: ${e.grimeAmp},`);
    lines.push(`    macroAmp: ${e.macroAmp},`);
    lines.push(`    scratchPer1000px2: ${e.scratchPer1000px2},`);
    lines.push(`    fleckPer1000px2: ${e.fleckPer1000px2},`);
    lines.push(`    scratchAngle: '${escapeStr(e.scratchAngle)}',`);
    lines.push(`    wallBodyKey: '${escapeStr(e.wallBodyKey)}',`);
    lines.push(`    wallRimKey: '${escapeStr(e.wallRimKey)}',`);
    lines.push(`    wallBv: ${e.wallBv},`);
    lines.push(`    wallBiasR: ${e.wallBiasR},`);
    lines.push(`    wallBiasG: ${e.wallBiasG},`);
    lines.push(`    wallBiasB: ${e.wallBiasB},`);
    lines.push(`    featureWidthTiles: ${e.featureWidthTiles},`);
    lines.push(`    featureLengthTiles: ${e.featureLengthTiles},`);
    lines.push(`    featureCountMin: ${e.featureCountMin},`);
    lines.push(`    featureCountMax: ${e.featureCountMax},`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  lines.push(
    'export const ENABLED_RIFT_FRAGMENTS: readonly RiftFragmentDef[] = Object.values(RIFT_FRAGMENT_DATA).filter((row) => row.enabled);',
  );
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'rift-fragment-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  rift-fragment-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Generate enemy-data.ts
// ---------------------------------------------------------------------------

function generateEnemies() {
  const { header, rows } = readCsv('enemies.csv');
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const requiredCols = [
    'id',
    'display_name',
    'role',
    'sight_range',
    'sight_half_angle_core',
    'sight_range_periph',
    'sight_half_angle_periph',
    'chase_sight_range',
    'hearing_range',
    'hearing_move_mult',
    'hearing_still_range',
    'hearing_wall_factor',
    'vision_weight',
    'hearing_weight',
    'hearing_max_push',
    'patrol_speed',
    'chase_speed',
    'suspicious_speed',
    'alert_speed',
    'return_speed',
  ];
  for (const col of requiredCols) {
    if (idx[col] === undefined) {
      throw new Error(`[codegen] enemies.csv missing column '${col}'`);
    }
  }

  const entries = rows.map((cols) => {
    const id = cols[idx.id];
    const role = cols[idx.role];
    const hearingMaxPush = cols[idx.hearing_max_push];
    if (role !== id) {
      throw new Error(`[codegen] enemies.csv role '${role}' must equal id '${id}'`);
    }
    if (hearingMaxPush !== 'suspicious' && hearingMaxPush !== 'alert') {
      throw new Error(`[codegen] enemies.csv ${id}: hearing_max_push must be suspicious|alert`);
    }
    return {
      id,
      displayName: cols[idx.display_name],
      role,
      sightRange: num(cols[idx.sight_range]),
      sightHalfAngleCore: num(cols[idx.sight_half_angle_core]),
      sightRangePeriph: num(cols[idx.sight_range_periph]),
      sightHalfAnglePeriph: num(cols[idx.sight_half_angle_periph]),
      chaseSightRange: num(cols[idx.chase_sight_range]),
      hearingRange: num(cols[idx.hearing_range]),
      hearingMoveMult: num(cols[idx.hearing_move_mult]),
      hearingStillRange: num(cols[idx.hearing_still_range]),
      hearingWallFactor: num(cols[idx.hearing_wall_factor]),
      visionWeight: num(cols[idx.vision_weight]),
      hearingWeight: num(cols[idx.hearing_weight]),
      hearingMaxPush,
      patrolSpeed: num(cols[idx.patrol_speed]),
      chaseSpeed: num(cols[idx.chase_speed]),
      suspiciousSpeed: num(cols[idx.suspicious_speed]),
      alertSpeed: num(cols[idx.alert_speed]),
      returnSpeed: num(cols[idx.return_speed]),
    };
  });

  const ids = new Set(entries.map((e) => e.id));
  for (const required of ['infiltrator', 'rewriter']) {
    if (!ids.has(required)) {
      throw new Error(`[codegen] enemies.csv missing required row '${required}'`);
    }
  }

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    '',
    "export type EnemyRole = 'infiltrator' | 'rewriter';",
    '',
    "export type HearingMaxPush = 'suspicious' | 'alert';",
    '',
    'export interface PerceptionProfile {',
    '  role: EnemyRole;',
    '  displayName: string;',
    '  sightRange: number;',
    '  sightHalfAngleCore: number;',
    '  sightRangePeriph: number;',
    '  sightHalfAnglePeriph: number;',
    '  chaseSightRange: number;',
    '  hearingRange: number;',
    '  hearingMoveMult: number;',
    '  hearingStillRange: number;',
    '  hearingWallFactor: number;',
    '  visionWeight: number;',
    '  hearingWeight: number;',
    '  hearingMaxPush: HearingMaxPush;',
    '  patrolSpeed: number;',
    '  chaseSpeed: number;',
    '  suspiciousSpeed: number;',
    '  alertSpeed: number;',
    '  returnSpeed: number;',
    '}',
    '',
    'export const ENEMY_DATA: Record<EnemyRole, PerceptionProfile> = {',
  ];

  for (const e of entries) {
    lines.push(`  ${e.id}: {`);
    lines.push(`    role: '${e.role}',`);
    lines.push(`    displayName: '${escapeStr(e.displayName)}',`);
    lines.push(`    sightRange: ${e.sightRange},`);
    lines.push(`    sightHalfAngleCore: ${e.sightHalfAngleCore},`);
    lines.push(`    sightRangePeriph: ${e.sightRangePeriph},`);
    lines.push(`    sightHalfAnglePeriph: ${e.sightHalfAnglePeriph},`);
    lines.push(`    chaseSightRange: ${e.chaseSightRange},`);
    lines.push(`    hearingRange: ${e.hearingRange},`);
    lines.push(`    hearingMoveMult: ${e.hearingMoveMult},`);
    lines.push(`    hearingStillRange: ${e.hearingStillRange},`);
    lines.push(`    hearingWallFactor: ${e.hearingWallFactor},`);
    lines.push(`    visionWeight: ${e.visionWeight},`);
    lines.push(`    hearingWeight: ${e.hearingWeight},`);
    lines.push(`    hearingMaxPush: '${e.hearingMaxPush}',`);
    lines.push(`    patrolSpeed: ${e.patrolSpeed},`);
    lines.push(`    chaseSpeed: ${e.chaseSpeed},`);
    lines.push(`    suspiciousSpeed: ${e.suspiciousSpeed},`);
    lines.push(`    alertSpeed: ${e.alertSpeed},`);
    lines.push(`    returnSpeed: ${e.returnSpeed},`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  lines.push("export const ENEMY_ROLES: readonly EnemyRole[] = ['infiltrator', 'rewriter'];");
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'enemy-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  enemy-data.ts (${entries.length} entries)`);
}

console.log('[codegen] Generating typed data from CSV...');
generateContaminants();
generateUpgrades();
generateRiftFragments();
generateEnemies();
console.log('[codegen] Done.');
