/**
 * CSV → TypeScript codegen.
 *
 * Reads data/*.csv and generates src/generated/*.ts with typed constants.
 * No external dependencies — uses built-in fs and simple comma-split parsing
 * (the CSV data uses Chinese punctuation, never ASCII commas inside fields).
 *
 * Usage: node tools/csv-codegen/generate.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const DATA_DIR = resolve(ROOT, 'data');
const OUT_DIR = resolve(ROOT, 'src/generated');

// Ensure output directory exists
mkdirSync(OUT_DIR, { recursive: true });

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Read a CSV file, strip BOM, return rows as string[][].
 * First row is the header.
 */
function readCsv(filename) {
  let raw = readFileSync(resolve(DATA_DIR, filename), 'utf-8');
  // Strip UTF-8 BOM (EF BB BF appears as ﻿ in the decoded string)
  if (raw.charCodeAt(0) === 0xfeff) {
    raw = raw.slice(1);
  }
  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);
  const header = lines[0].split(',');
  const rows = lines.slice(1).map((line) => line.split(','));
  return { header, rows };
}

/** Convert snake_case to camelCase. */
function toCamel(s) {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** Escape a string for use inside a TS template literal or single-quoted string. */
function escapeStr(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

// ---------------------------------------------------------------------------
// Generate contaminant-data.ts
// ---------------------------------------------------------------------------

function generateContaminants() {
  const { header, rows } = readCsv('contaminants.csv');

  // Map header indices
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => ({
    id: cols[idx.id],
    rarity: cols[idx.rarity],
    displayNameDefense: cols[idx.display_name_defense],
    descriptionDefense: cols[idx.description_defense],
    summaryDefense: cols[idx.summary_defense] ?? '',
    defenseCategory: cols[idx.defense_category],
    defenseReduction: parseFloat(cols[idx.defense_reduction]),
    defenseSideEffect: cols[idx.defense_side_effect],
    sideEffectDuration: cols[idx.side_effect_duration],
    defenseChargeMult: parseFloat(cols[idx.defense_charge_mult]),
    displayNameTool: cols[idx.display_name_tool],
    descriptionTool: cols[idx.description_tool],
    summaryTool: cols[idx.summary_tool] ?? '',
    toolType: cols[idx.tool_type],
    toolUses: parseInt(cols[idx.tool_uses], 10),
    toolRangePx: parseInt(cols[idx.tool_range_px], 10),
    toolDurationMs: parseInt(cols[idx.tool_duration_ms], 10),
    narrativeOrigin: cols[idx.narrative_origin],
  }));

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    "import type { ContaminantType, ContaminantRarity } from '@/types/game-types';",
    '',
    'export interface ContaminantDef {',
    '  id: ContaminantType;',
    '  rarity: ContaminantRarity;',
    '  displayNameDefense: string;',
    '  descriptionDefense: string;',
    '  summaryDefense: string;',
    '  defenseCategory: string;',
    '  defenseReduction: number;',
    '  defenseSideEffect: string;',
    '  sideEffectDuration: string;',
    '  defenseChargeMult: number;',
    '  displayNameTool: string;',
    '  descriptionTool: string;',
    '  summaryTool: string;',
    "  toolType: 'active' | 'passive';",
    '  toolUses: number;',
    '  toolRangePx: number;',
    '  toolDurationMs: number;',
    '  narrativeOrigin: string;',
    '}',
    '',
    'export const CONTAMINANT_DATA: Record<ContaminantType, ContaminantDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${e.id}',`);
    lines.push(`    rarity: '${e.rarity}',`);
    lines.push(`    displayNameDefense: '${escapeStr(e.displayNameDefense)}',`);
    lines.push(`    descriptionDefense: '${escapeStr(e.descriptionDefense)}',`);
    lines.push(`    summaryDefense: '${escapeStr(e.summaryDefense)}',`);
    lines.push(`    defenseCategory: '${escapeStr(e.defenseCategory)}',`);
    lines.push(`    defenseReduction: ${e.defenseReduction},`);
    lines.push(`    defenseSideEffect: '${escapeStr(e.defenseSideEffect)}',`);
    lines.push(`    sideEffectDuration: '${escapeStr(e.sideEffectDuration)}',`);
    lines.push(`    defenseChargeMult: ${e.defenseChargeMult},`);
    lines.push(`    displayNameTool: '${escapeStr(e.displayNameTool)}',`);
    lines.push(`    descriptionTool: '${escapeStr(e.descriptionTool)}',`);
    lines.push(`    summaryTool: '${escapeStr(e.summaryTool)}',`);
    lines.push(`    toolType: '${e.toolType}',`);
    lines.push(`    toolUses: ${e.toolUses},`);
    lines.push(`    toolRangePx: ${e.toolRangePx},`);
    lines.push(`    toolDurationMs: ${e.toolDurationMs},`);
    lines.push(`    narrativeOrigin: '${escapeStr(e.narrativeOrigin)}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'contaminant-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  contaminant-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Generate upgrade-data.ts
// ---------------------------------------------------------------------------

function generateUpgrades() {
  const { header, rows } = readCsv('upgrades.csv');
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => {
    const maxLevel = parseInt(cols[idx.max_level], 10);
    const costs = [];
    for (let i = 1; i <= 5; i++) {
      const val = cols[idx[`cost_${i}`]];
      if (val && val.trim() !== '') {
        costs.push(parseInt(val, 10));
      }
    }
    return {
      id: cols[idx.id],
      axis: cols[idx.axis],
      maxLevel,
      effectPerLevel: parseFloat(cols[idx.effect_per_level]),
      effectUnit: cols[idx.effect_unit],
      costs,
      description: cols[idx.description]?.trim() ?? '',
    };
  });

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    "import type { GrowthUpgradeId } from '@/types/game-types';",
    '',
    'export interface UpgradeDef {',
    '  id: GrowthUpgradeId;',
    '  axis: string;',
    '  maxLevel: number;',
    '  effectPerLevel: number;',
    '  effectUnit: string;',
    '  costs: number[];',
    '  description: string;',
    '}',
    '',
    'export const UPGRADE_DATA: Record<GrowthUpgradeId, UpgradeDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${e.id}',`);
    lines.push(`    axis: '${escapeStr(e.axis)}',`);
    lines.push(`    maxLevel: ${e.maxLevel},`);
    lines.push(`    effectPerLevel: ${e.effectPerLevel},`);
    lines.push(`    effectUnit: '${escapeStr(e.effectUnit)}',`);
    lines.push(`    costs: [${e.costs.join(', ')}],`);
    lines.push(`    description: '${escapeStr(e.description)}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'upgrade-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  upgrade-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

console.log('[codegen] Generating typed data from CSV...');
generateContaminants();
generateUpgrades();
console.log('[codegen] Done.');
