/**
 * CSV → TypeScript codegen.
 *
 * Reads data/*.csv and generates src/generated/*.ts with typed constants.
 * No external dependencies — uses built-in fs and simple comma-split parsing
 * (the CSV data uses Chinese punctuation, never ASCII commas inside fields).
 *
 * Usage: node tools/csv-codegen/generate.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const DATA_DIR = resolve(ROOT, 'data');
const OUT_DIR = resolve(ROOT, 'src/generated');

// Ensure output directory exists
mkdirSync(OUT_DIR, { recursive: true });

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Read a CSV file, strip BOM, return rows as string[][].
 * First row is the header.
 */
function readCsv(filename) {
  let raw = readFileSync(resolve(DATA_DIR, filename), 'utf-8');
  // Strip UTF-8 BOM (EF BB BF appears as ﻿ in the decoded string)
  if (raw.charCodeAt(0) === 0xfeff) {
    raw = raw.slice(1);
  }
  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);
  const header = lines[0].split(',');
  const rows = lines.slice(1).map((line) => line.split(','));
  return { header, rows };
}

/** Convert snake_case to camelCase. */
function toCamel(s) {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** Escape a string for use inside a TS template literal or single-quoted string. */
function escapeStr(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

// ---------------------------------------------------------------------------
// Generate contaminant-data.ts
// ---------------------------------------------------------------------------

function generateContaminants() {
  const { header, rows } = readCsv('contaminants.csv');

  // Map header indices
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => ({
    id: cols[idx.id],
    rarity: cols[idx.rarity],
    displayNameDefense: cols[idx.display_name_defense],
    descriptionDefense: cols[idx.description_defense],
    summaryDefense: cols[idx.summary_defense] ?? '',
    defenseCategory: cols[idx.defense_category],
    defenseReduction: parseFloat(cols[idx.defense_reduction]),
    defenseSideEffect: cols[idx.defense_side_effect],
    sideEffectDuration: cols[idx.side_effect_duration],
    defenseChargeMult: parseFloat(cols[idx.defense_charge_mult]),
    displayNameTool: cols[idx.display_name_tool],
    descriptionTool: cols[idx.description_tool],
    summaryTool: cols[idx.summary_tool] ?? '',
    toolType: cols[idx.tool_type],
    toolUses: parseInt(cols[idx.tool_uses], 10),
    toolRangePx: parseInt(cols[idx.tool_range_px], 10),
    toolDurationMs: parseInt(cols[idx.tool_duration_ms], 10),
    narrativeOrigin: cols[idx.narrative_origin],
  }));

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    "import type { ContaminantType, ContaminantRarity } from '@/types/game-types';",
    '',
    'export interface ContaminantDef {',
    '  id: ContaminantType;',
    '  rarity: ContaminantRarity;',
    '  displayNameDefense: string;',
    '  descriptionDefense: string;',
    '  summaryDefense: string;',
    '  defenseCategory: string;',
    '  defenseReduction: number;',
    '  defenseSideEffect: string;',
    '  sideEffectDuration: string;',
    '  defenseChargeMult: number;',
    '  displayNameTool: string;',
    '  descriptionTool: string;',
    '  summaryTool: string;',
    "  toolType: 'active' | 'passive';",
    '  toolUses: number;',
    '  toolRangePx: number;',
    '  toolDurationMs: number;',
    '  narrativeOrigin: string;',
    '}',
    '',
    'export const CONTAMINANT_DATA: Record<ContaminantType, ContaminantDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${e.id}',`);
    lines.push(`    rarity: '${e.rarity}',`);
    lines.push(`    displayNameDefense: '${escapeStr(e.displayNameDefense)}',`);
    lines.push(`    descriptionDefense: '${escapeStr(e.descriptionDefense)}',`);
    lines.push(`    summaryDefense: '${escapeStr(e.summaryDefense)}',`);
    lines.push(`    defenseCategory: '${escapeStr(e.defenseCategory)}',`);
    lines.push(`    defenseReduction: ${e.defenseReduction},`);
    lines.push(`    defenseSideEffect: '${escapeStr(e.defenseSideEffect)}',`);
    lines.push(`    sideEffectDuration: '${escapeStr(e.sideEffectDuration)}',`);
    lines.push(`    defenseChargeMult: ${e.defenseChargeMult},`);
    lines.push(`    displayNameTool: '${escapeStr(e.displayNameTool)}',`);
    lines.push(`    descriptionTool: '${escapeStr(e.descriptionTool)}',`);
    lines.push(`    summaryTool: '${escapeStr(e.summaryTool)}',`);
    lines.push(`    toolType: '${e.toolType}',`);
    lines.push(`    toolUses: ${e.toolUses},`);
    lines.push(`    toolRangePx: ${e.toolRangePx},`);
    lines.push(`    toolDurationMs: ${e.toolDurationMs},`);
    lines.push(`    narrativeOrigin: '${escapeStr(e.narrativeOrigin)}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'contaminant-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  contaminant-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Generate upgrade-data.ts
// ---------------------------------------------------------------------------

function generateUpgrades() {
  const { header, rows } = readCsv('upgrades.csv');
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => {
    const maxLevel = parseInt(cols[idx.max_level], 10);
    const costs = [];
    for (let i = 1; i <= 5; i++) {
      const val = cols[idx[`cost_${i}`]];
      if (val && val.trim() !== '') {
        costs.push(parseInt(val, 10));
      }
    }
    return {
      id: cols[idx.id],
      axis: cols[idx.axis],
      maxLevel,
      effectPerLevel: parseFloat(cols[idx.effect_per_level]),
      effectUnit: cols[idx.effect_unit],
      costs,
      description: cols[idx.description]?.trim() ?? '',
    };
  });

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    "import type { GrowthUpgradeId } from '@/types/game-types';",
    '',
    'export interface UpgradeDef {',
    '  id: GrowthUpgradeId;',
    '  axis: string;',
    '  maxLevel: number;',
    '  effectPerLevel: number;',
    '  effectUnit: string;',
    '  costs: number[];',
    '  description: string;',
    '}',
    '',
    'export const UPGRADE_DATA: Record<GrowthUpgradeId, UpgradeDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${e.id}',`);
    lines.push(`    axis: '${escapeStr(e.axis)}',`);
    lines.push(`    maxLevel: ${e.maxLevel},`);
    lines.push(`    effectPerLevel: ${e.effectPerLevel},`);
    lines.push(`    effectUnit: '${escapeStr(e.effectUnit)}',`);
    lines.push(`    costs: [${e.costs.join(', ')}],`);
    lines.push(`    description: '${escapeStr(e.description)}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'upgrade-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  upgrade-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function num(s) {
  if (s === undefined || s === null || String(s).trim() === '') return 0;
  return parseFloat(s);
}

function flag(s) {
  const v = String(s ?? '').trim().toLowerCase();
  return v === 'true' || v === '1';
}

function generateRiftFragments() {
  const { header, rows } = readCsv('rift-fragments.csv');
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const entries = rows.map((cols) => ({
    id: cols[idx.id],
    displayName: cols[idx.display_name],
    l1Key: cols[idx.l1_key],
    sourceDomain: cols[idx.source_domain],
    coverage: cols[idx.coverage],
    massGrammar: cols[idx.mass_grammar],
    join: cols[idx.join],
    surfaceMaterial: cols[idx.surface_material],
    enabled: flag(cols[idx.enabled]),
    floorBv: num(cols[idx.floor_bv]),
    floorBiasR: num(cols[idx.floor_bias_r]),
    floorBiasG: num(cols[idx.floor_bias_g]),
    floorBiasB: num(cols[idx.floor_bias_b]),
    stainKey: cols[idx.stain_key] ?? '',
    stainThreshold: num(cols[idx.stain_threshold]),
    stainStrength: num(cols[idx.stain_strength]),
    grimeAmp: num(cols[idx.grime_amp]),
    macroAmp: num(cols[idx.macro_amp]),
    scratchPer1000px2: num(cols[idx.scratch_per_1000px2]),
    fleckPer1000px2: num(cols[idx.fleck_per_1000px2]),
    scratchAngle: cols[idx.scratch_angle] ?? '',
    wallBodyKey: cols[idx.wall_body_key] ?? '',
    wallRimKey: cols[idx.wall_rim_key] ?? '',
    wallBv: num(cols[idx.wall_bv]),
    wallBiasR: num(cols[idx.wall_bias_r]),
    wallBiasG: num(cols[idx.wall_bias_g]),
    wallBiasB: num(cols[idx.wall_bias_b]),
    featureWidthTiles: num(cols[idx.feature_width_tiles]),
    featureLengthTiles: num(cols[idx.feature_length_tiles]),
    featureCountMin: num(cols[idx.feature_count_min]),
    featureCountMax: num(cols[idx.feature_count_max]),
  }));

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    '',
    'export type SourceDomain = \'mundane\' | \'virtual\' | \'alien\';',
    '',
    'export type Coverage = \'remnant\' | \'half\' | \'unnamed\';',
    '',
    'export type MassGrammar =',
    "  | 'enclosure'",
    "  | 'ridge'",
    "  | 'cluster'",
    "  | 'slab'",
    "  | 'lattice'",
    "  | 'growth';",
    '',
    "export type FragmentJoin = 'single' | 'shear';",
    '',
    "export type ScratchAngle = 'free' | 'orthogonal' | 'longitudinal' | '';",
    '',
    'export interface RiftFragmentDef {',
    '  id: string;',
    '  displayName: string;',
    '  l1Key: string;',
    '  sourceDomain: SourceDomain;',
    '  coverage: Coverage;',
    '  massGrammar: MassGrammar;',
    '  join: FragmentJoin;',
    '  surfaceMaterial: string;',
    '  enabled: boolean;',
    '  floorBv: number;',
    '  floorBiasR: number;',
    '  floorBiasG: number;',
    '  floorBiasB: number;',
    '  stainKey: string;',
    '  stainThreshold: number;',
    '  stainStrength: number;',
    '  grimeAmp: number;',
    '  macroAmp: number;',
    '  scratchPer1000px2: number;',
    '  fleckPer1000px2: number;',
    '  scratchAngle: ScratchAngle;',
    '  wallBodyKey: string;',
    '  wallRimKey: string;',
    '  wallBv: number;',
    '  wallBiasR: number;',
    '  wallBiasG: number;',
    '  wallBiasB: number;',
    '  featureWidthTiles: number;',
    '  featureLengthTiles: number;',
    '  featureCountMin: number;',
    '  featureCountMax: number;',
    '}',
    '',
    'export const RIFT_FRAGMENT_DATA: Record<string, RiftFragmentDef> = {',
  ];

  for (const e of entries) {
    lines.push(`  '${e.id}': {`);
    lines.push(`    id: '${escapeStr(e.id)}',`);
    lines.push(`    displayName: '${escapeStr(e.displayName)}',`);
    lines.push(`    l1Key: '${escapeStr(e.l1Key)}',`);
    lines.push(`    sourceDomain: '${escapeStr(e.sourceDomain)}',`);
    lines.push(`    coverage: '${escapeStr(e.coverage)}',`);
    lines.push(`    massGrammar: '${escapeStr(e.massGrammar)}',`);
    lines.push(`    join: '${escapeStr(e.join)}',`);
    lines.push(`    surfaceMaterial: '${escapeStr(e.surfaceMaterial)}',`);
    lines.push(`    enabled: ${e.enabled},`);
    lines.push(`    floorBv: ${e.floorBv},`);
    lines.push(`    floorBiasR: ${e.floorBiasR},`);
    lines.push(`    floorBiasG: ${e.floorBiasG},`);
    lines.push(`    floorBiasB: ${e.floorBiasB},`);
    lines.push(`    stainKey: '${escapeStr(e.stainKey)}',`);
    lines.push(`    stainThreshold: ${e.stainThreshold},`);
    lines.push(`    stainStrength: ${e.stainStrength},`);
    lines.push(`    grimeAmp: ${e.grimeAmp},`);
    lines.push(`    macroAmp: ${e.macroAmp},`);
    lines.push(`    scratchPer1000px2: ${e.scratchPer1000px2},`);
    lines.push(`    fleckPer1000px2: ${e.fleckPer1000px2},`);
    lines.push(`    scratchAngle: '${escapeStr(e.scratchAngle)}',`);
    lines.push(`    wallBodyKey: '${escapeStr(e.wallBodyKey)}',`);
    lines.push(`    wallRimKey: '${escapeStr(e.wallRimKey)}',`);
    lines.push(`    wallBv: ${e.wallBv},`);
    lines.push(`    wallBiasR: ${e.wallBiasR},`);
    lines.push(`    wallBiasG: ${e.wallBiasG},`);
    lines.push(`    wallBiasB: ${e.wallBiasB},`);
    lines.push(`    featureWidthTiles: ${e.featureWidthTiles},`);
    lines.push(`    featureLengthTiles: ${e.featureLengthTiles},`);
    lines.push(`    featureCountMin: ${e.featureCountMin},`);
    lines.push(`    featureCountMax: ${e.featureCountMax},`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  lines.push(
    'export const ENABLED_RIFT_FRAGMENTS: readonly RiftFragmentDef[] = Object.values(RIFT_FRAGMENT_DATA).filter((row) => row.enabled);',
  );
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'rift-fragment-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  rift-fragment-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Generate enemy-data.ts
// ---------------------------------------------------------------------------

function generateEnemies() {
  const { header, rows } = readCsv('enemies.csv');
  const idx = Object.fromEntries(header.map((h, i) => [h, i]));

  const requiredCols = [
    'id',
    'display_name',
    'role',
    'sight_range',
    'sight_half_angle_core',
    'sight_range_periph',
    'sight_half_angle_periph',
    'chase_sight_range',
    'hearing_range',
    'hearing_move_mult',
    'hearing_still_range',
    'hearing_wall_factor',
    'vision_weight',
    'hearing_weight',
    'hearing_max_push',
    'patrol_speed',
    'chase_speed',
    'suspicious_speed',
    'alert_speed',
    'return_speed',
  ];
  for (const col of requiredCols) {
    if (idx[col] === undefined) {
      throw new Error(`[codegen] enemies.csv missing column '${col}'`);
    }
  }

  const entries = rows.map((cols) => {
    const id = cols[idx.id];
    const role = cols[idx.role];
    const hearingMaxPush = cols[idx.hearing_max_push];
    if (role !== id) {
      throw new Error(`[codegen] enemies.csv role '${role}' must equal id '${id}'`);
    }
    if (hearingMaxPush !== 'suspicious' && hearingMaxPush !== 'alert') {
      throw new Error(`[codegen] enemies.csv ${id}: hearing_max_push must be suspicious|alert`);
    }
    return {
      id,
      displayName: cols[idx.display_name],
      role,
      sightRange: num(cols[idx.sight_range]),
      sightHalfAngleCore: num(cols[idx.sight_half_angle_core]),
      sightRangePeriph: num(cols[idx.sight_range_periph]),
      sightHalfAnglePeriph: num(cols[idx.sight_half_angle_periph]),
      chaseSightRange: num(cols[idx.chase_sight_range]),
      hearingRange: num(cols[idx.hearing_range]),
      hearingMoveMult: num(cols[idx.hearing_move_mult]),
      hearingStillRange: num(cols[idx.hearing_still_range]),
      hearingWallFactor: num(cols[idx.hearing_wall_factor]),
      visionWeight: num(cols[idx.vision_weight]),
      hearingWeight: num(cols[idx.hearing_weight]),
      hearingMaxPush,
      patrolSpeed: num(cols[idx.patrol_speed]),
      chaseSpeed: num(cols[idx.chase_speed]),
      suspiciousSpeed: num(cols[idx.suspicious_speed]),
      alertSpeed: num(cols[idx.alert_speed]),
      returnSpeed: num(cols[idx.return_speed]),
    };
  });

  const ids = new Set(entries.map((e) => e.id));
  for (const required of ['infiltrator', 'rewriter']) {
    if (!ids.has(required)) {
      throw new Error(`[codegen] enemies.csv missing required row '${required}'`);
    }
  }

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    '',
    "export type EnemyRole = 'infiltrator' | 'rewriter';",
    '',
    "export type HearingMaxPush = 'suspicious' | 'alert';",
    '',
    'export interface PerceptionProfile {',
    '  role: EnemyRole;',
    '  displayName: string;',
    '  sightRange: number;',
    '  sightHalfAngleCore: number;',
    '  sightRangePeriph: number;',
    '  sightHalfAnglePeriph: number;',
    '  chaseSightRange: number;',
    '  hearingRange: number;',
    '  hearingMoveMult: number;',
    '  hearingStillRange: number;',
    '  hearingWallFactor: number;',
    '  visionWeight: number;',
    '  hearingWeight: number;',
    '  hearingMaxPush: HearingMaxPush;',
    '  patrolSpeed: number;',
    '  chaseSpeed: number;',
    '  suspiciousSpeed: number;',
    '  alertSpeed: number;',
    '  returnSpeed: number;',
    '}',
    '',
    'export const ENEMY_DATA: Record<EnemyRole, PerceptionProfile> = {',
  ];

  for (const e of entries) {
    lines.push(`  ${e.id}: {`);
    lines.push(`    role: '${e.role}',`);
    lines.push(`    displayName: '${escapeStr(e.displayName)}',`);
    lines.push(`    sightRange: ${e.sightRange},`);
    lines.push(`    sightHalfAngleCore: ${e.sightHalfAngleCore},`);
    lines.push(`    sightRangePeriph: ${e.sightRangePeriph},`);
    lines.push(`    sightHalfAnglePeriph: ${e.sightHalfAnglePeriph},`);
    lines.push(`    chaseSightRange: ${e.chaseSightRange},`);
    lines.push(`    hearingRange: ${e.hearingRange},`);
    lines.push(`    hearingMoveMult: ${e.hearingMoveMult},`);
    lines.push(`    hearingStillRange: ${e.hearingStillRange},`);
    lines.push(`    hearingWallFactor: ${e.hearingWallFactor},`);
    lines.push(`    visionWeight: ${e.visionWeight},`);
    lines.push(`    hearingWeight: ${e.hearingWeight},`);
    lines.push(`    hearingMaxPush: '${e.hearingMaxPush}',`);
    lines.push(`    patrolSpeed: ${e.patrolSpeed},`);
    lines.push(`    chaseSpeed: ${e.chaseSpeed},`);
    lines.push(`    suspiciousSpeed: ${e.suspiciousSpeed},`);
    lines.push(`    alertSpeed: ${e.alertSpeed},`);
    lines.push(`    returnSpeed: ${e.returnSpeed},`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  lines.push("export const ENEMY_ROLES: readonly EnemyRole[] = ['infiltrator', 'rewriter'];");
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'enemy-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  enemy-data.ts (${entries.length} entries)`);
}

// ---------------------------------------------------------------------------
// Generate contamination-lexicon-data.ts
// ---------------------------------------------------------------------------

function splitBar(s) {
  return (s ?? '')
    .split('|')
    .map((part) => part.trim())
    .filter((part) => part.length > 0);
}

function parseBool(s, col, id) {
  if (s === 'true') return true;
  if (s === 'false') return false;
  throw new Error(`[codegen] contamination ${id}: ${col} must be true|false (got '${s}')`);
}

function parseRewrites(s) {
  if (!s) return [];
  return s.split(';').filter(Boolean).map((pair) => {
    const [portfolio, lexeme] = pair.split(':');
    if (!portfolio || !lexeme) {
      throw new Error(`[codegen] rewrite_to must be portfolio:lexeme (; separated), got '${s}'`);
    }
    return { portfolio, lexeme };
  });
}

function generateContaminationLexicon() {
  const substratesCsv = readCsv('contamination-substrates.csv');
  const portfoliosCsv = readCsv('contamination-portfolios.csv');
  const lexemesCsv = readCsv('contamination-lexemes.csv');
  const utterancesCsv = readCsv('contamination-utterances.csv');
  const tokensCsv = readCsv('contamination-display-tokens.csv');

  const sIdx = Object.fromEntries(substratesCsv.header.map((h, i) => [h, i]));
  const pIdx = Object.fromEntries(portfoliosCsv.header.map((h, i) => [h, i]));
  const lIdx = Object.fromEntries(lexemesCsv.header.map((h, i) => [h, i]));
  const uIdx = Object.fromEntries(utterancesCsv.header.map((h, i) => [h, i]));
  const tIdx = Object.fromEntries(tokensCsv.header.map((h, i) => [h, i]));

  const requiredSub = [
    'id',
    'display_token',
    'residual_verb',
    'legal_occupancies',
    'legal_continuities',
    'enabled_scope',
  ];
  for (const col of requiredSub) {
    if (sIdx[col] === undefined) throw new Error(`[codegen] contamination-substrates.csv missing '${col}'`);
  }

  const OCC_OK = new Set(['floor', 'wall', 'paint', 'volume']);
  const CONT_OK = new Set(['monolith', 'shards', 'colony', 'field']);
  const SCOPE_OK = new Set(['sortie', 'gym']);
  /** Spec conceptual substrates (volume-only). Pairing: sortie-open ↔ oil_film drops volume. */
  const CONCEPTUAL_SUBSTRATE_IDS = ['sound_echo', 'light_scatter', 'space_interval'];

  const substrates = substratesCsv.rows.map((cols) => {
    if (cols.length !== substratesCsv.header.length) {
      throw new Error(
        `[codegen] contamination-substrates.csv row '${cols[sIdx.id]}' has ${cols.length} fields, expected ${substratesCsv.header.length}`,
      );
    }
    const id = cols[sIdx.id];
    const enabledScope = cols[sIdx.enabled_scope];
    if (!SCOPE_OK.has(enabledScope)) {
      throw new Error(`[codegen] contamination-substrates.csv ${id}: enabled_scope must be sortie|gym (got '${enabledScope}')`);
    }
    const legalOccupancies = splitBar(cols[sIdx.legal_occupancies]);
    const legalContinuities = splitBar(cols[sIdx.legal_continuities]);
    for (const occ of legalOccupancies) {
      if (!OCC_OK.has(occ)) throw new Error(`[codegen] contamination-substrates.csv ${id}: illegal occupancy '${occ}'`);
    }
    for (const cont of legalContinuities) {
      if (!CONT_OK.has(cont)) throw new Error(`[codegen] contamination-substrates.csv ${id}: illegal continuity '${cont}'`);
    }
    return {
      id,
      displayToken: cols[sIdx.display_token],
      residualVerb: cols[sIdx.residual_verb],
      legalOccupancies,
      legalContinuities,
      enabledScope,
    };
  });
  const subIds = new Set(substrates.map((s) => s.id));
  for (const required of [
    'organic_remnant',
    'lamp_pillar',
    'doorframe',
    'wall_rust',
    'fungal_mat',
    'oil_film',
    ...CONCEPTUAL_SUBSTRATE_IDS,
  ]) {
    if (!subIds.has(required)) throw new Error(`[codegen] contamination-substrates.csv missing '${required}'`);
  }

  const conceptualOnSortie = CONCEPTUAL_SUBSTRATE_IDS.some((id) => {
    const row = substrates.find((s) => s.id === id);
    return row?.enabledScope === 'sortie';
  });
  for (const s of substrates) {
    s.sortieLegalOccupancies =
      s.id === 'oil_film' && !conceptualOnSortie && !s.legalOccupancies.includes('volume')
        ? [...s.legalOccupancies, 'volume']
        : s.legalOccupancies;
  }
  const sortieSubstrates = substrates.filter((s) => s.enabledScope === 'sortie');

  const portfolios = portfoliosCsv.rows.map((cols) => {
    const id = cols[pIdx.id];
    return {
      id,
      displayToken: cols[pIdx.display_token],
      continuity: cols[pIdx.continuity],
      occupancy: cols[pIdx.occupancy],
      legalContinuities: splitBar(cols[pIdx.legal_continuities]),
      pinLayer: cols[pIdx.pin_layer],
      canChase: parseBool(cols[pIdx.can_chase], 'can_chase', id),
      blockWalk: parseBool(cols[pIdx.block_walk], 'block_walk', id),
      defaultContact: cols[pIdx.default_contact],
      detectionPulse: parseBool(cols[pIdx.detection_pulse], 'detection_pulse', id),
    };
  });
  const portIds = new Set(portfolios.map((p) => p.id));
  for (const required of ['jia', 'yi', 'bing', 'ding']) {
    if (!portIds.has(required)) throw new Error(`[codegen] contamination-portfolios.csv missing '${required}'`);
  }

  const lexemes = lexemesCsv.rows.map((cols) => {
    const slot = cols[lIdx.slot];
    if (!['motion', 'sense', 'rhythm', 'contact'].includes(slot)) {
      throw new Error(`[codegen] lexeme ${cols[lIdx.id]} slot must be motion|sense|rhythm|contact`);
    }
    return {
      id: cols[lIdx.id],
      slot,
      displayToken: cols[lIdx.display_token],
      legalPortfolios: splitBar(cols[lIdx.legal_portfolios]),
      rewrites: parseRewrites(cols[lIdx.rewrite_to] ?? ''),
    };
  });

  const utterances = utterancesCsv.rows.map((cols) => ({
    id: cols[uIdx.id],
    internalLabel: cols[uIdx.internal_label],
    onScreenMark: cols[uIdx.on_screen_mark],
    coverage: cols[uIdx.coverage],
    substrate: cols[uIdx.substrate],
    portfolio: cols[uIdx.portfolio],
    continuity: cols[uIdx.continuity],
    occupancy: cols[uIdx.occupancy],
    motion: cols[uIdx.motion],
    sense: cols[uIdx.sense],
    rhythm: cols[uIdx.rhythm],
    contact: cols[uIdx.contact],
  }));
  const uttIds = new Set(utterances.map((u) => u.id));
  for (const required of ['door_still_closing', 'eye_in_the_seam', 'cluster_lung', 'corridor_watching']) {
    if (!uttIds.has(required)) throw new Error(`[codegen] contamination-utterances.csv missing '${required}'`);
  }

  const displayTokens = tokensCsv.rows.map((cols) => ({
    id: cols[tIdx.id],
    kind: cols[tIdx.kind],
    displayToken: cols[tIdx.display_token],
  }));

  if (lexemes.some((l) => l.id === 'contact_disperse_core')) {
    throw new Error('[codegen] contamination-lexemes.csv must not contain contact_disperse_core');
  }
  const melee = lexemes.find((l) => l.id === 'contact_melee_three');
  if (!melee) throw new Error('[codegen] contamination-lexemes.csv missing contact_melee_three');
  const meleeWant = {
    yi: 'contact_adjacent_strike',
    bing: 'contact_step_chaos',
    ding: 'contact_volume_chaos',
  };
  for (const [portfolio, lexeme] of Object.entries(meleeWant)) {
    const hit = melee.rewrites.find((r) => r.portfolio === portfolio);
    if (!hit || hit.lexeme !== lexeme) {
      throw new Error(
        `[codegen] contact_melee_three.rewrite_to must include ${portfolio}:${lexeme}`,
      );
    }
  }
  if (lexemes.some((l) => l.rewrites.some((r) => r.lexeme === 'contact_disperse_core'))) {
    throw new Error('[codegen] rewrite_to must not point at contact_disperse_core');
  }

  const stopCsv = readCsv('contamination-stop-loss.csv');
  const slIdx = Object.fromEntries(stopCsv.header.map((h, i) => [h, i]));
  const stopRequired = ['id', 'continuity', 'coverage', 'family', 'core_policy', 'legal_occupancies'];
  for (const col of stopRequired) {
    if (slIdx[col] === undefined) {
      throw new Error(`[codegen] contamination-stop-loss.csv missing '${col}'`);
    }
  }
  if (stopCsv.rows.length !== 9) {
    throw new Error(`[codegen] contamination-stop-loss.csv must have exactly 9 rows (got ${stopCsv.rows.length})`);
  }
  const FAMILY_OK = new Set(['core_strike', 'scatter_rejoin', 'unkillable']);
  const POLICY_OK = new Set(['exposed', 'standard', 'obscured', 'none']);
  const COVER_OK = new Set(['infiltrate', 'rewrite', 'overwrite']);
  const STOP_CONT_OK = new Set(['monolith', 'colony', 'field']);
  const stopLoss = stopCsv.rows.map((cols, rowI) => {
    if (cols.length !== stopCsv.header.length) {
      throw new Error(
        `[codegen] contamination-stop-loss.csv row ${rowI + 2} has ${cols.length} fields, expected ${stopCsv.header.length} (ASCII comma in a field?)`,
      );
    }
    const id = cols[slIdx.id];
    const continuity = cols[slIdx.continuity];
    const coverage = cols[slIdx.coverage];
    const family = cols[slIdx.family];
    const corePolicy = cols[slIdx.core_policy];
    const legalOccupancies = splitBar(cols[slIdx.legal_occupancies]);
    if (continuity === 'shards' || !STOP_CONT_OK.has(continuity)) {
      throw new Error(`[codegen] contamination-stop-loss.csv ${id}: shards / illegal continuity '${continuity}'`);
    }
    if (!COVER_OK.has(coverage)) {
      throw new Error(`[codegen] contamination-stop-loss.csv ${id}: illegal coverage '${coverage}'`);
    }
    if (id !== `${continuity}_${coverage}`) {
      throw new Error(`[codegen] contamination-stop-loss.csv id '${id}' must be ${continuity}_${coverage}`);
    }
    if (!FAMILY_OK.has(family)) {
      throw new Error(`[codegen] contamination-stop-loss.csv ${id}: illegal family '${family}'`);
    }
    if (!POLICY_OK.has(corePolicy)) {
      throw new Error(`[codegen] contamination-stop-loss.csv ${id}: illegal core_policy '${corePolicy}'`);
    }
    if (family === 'unkillable' && corePolicy !== 'none') {
      throw new Error(`[codegen] contamination-stop-loss.csv ${id}: unkillable core_policy must be none`);
    }
    if (family !== 'unkillable' && corePolicy === 'none') {
      throw new Error(`[codegen] contamination-stop-loss.csv ${id}: ${family} core_policy must not be none`);
    }
    for (const occ of legalOccupancies) {
      if (!OCC_OK.has(occ)) {
        throw new Error(`[codegen] contamination-stop-loss.csv ${id}: illegal occupancy '${occ}'`);
      }
    }
    if (family === 'unkillable') {
      const set = new Set(legalOccupancies);
      if (set.size !== 2 || !set.has('paint') || !set.has('volume')) {
        throw new Error(`[codegen] contamination-stop-loss.csv ${id}: unkillable legal_occupancies must be paint|volume`);
      }
    }
    if (family === 'scatter_rejoin' && legalOccupancies.includes('floor')) {
      throw new Error(`[codegen] contamination-stop-loss.csv ${id}: scatter_rejoin must not include floor`);
    }
    return { id, continuity, coverage, family, corePolicy, legalOccupancies };
  });
  const stopIds = new Set(stopLoss.map((s) => s.id));
  for (const continuity of STOP_CONT_OK) {
    for (const coverage of COVER_OK) {
      const want = `${continuity}_${coverage}`;
      if (!stopIds.has(want)) {
        throw new Error(`[codegen] contamination-stop-loss.csv missing '${want}'`);
      }
    }
  }

  const lines = [
    '// AUTO-GENERATED by tools/csv-codegen/generate.mjs — DO NOT EDIT',
    '',
    "export type CoverageId = 'infiltrate' | 'rewrite' | 'overwrite';",
    "export type OccupancyId = 'floor' | 'wall' | 'paint' | 'volume';",
    "export type ContinuityId = 'monolith' | 'shards' | 'colony' | 'field';",
    "export type PortfolioId = 'jia' | 'yi' | 'bing' | 'ding';",
    "export type LexemeSlot = 'motion' | 'sense' | 'rhythm' | 'contact';",
    "export type PinLayerId = 'waypoints' | 'wall_edge' | 'cluster_core' | 'corridor_aabb';",
    "export type SubstrateEnabledScope = 'sortie' | 'gym';",
    '',
    'export interface SubstrateDef {',
    '  id: string;',
    '  displayToken: string;',
    '  residualVerb: string;',
    '  /** CSV / gym view. */',
    '  legalOccupancies: readonly OccupancyId[];',
    '  /** Sortie view (oil_film volume overlay while conceptual substrates stay gym). */',
    '  sortieLegalOccupancies: readonly OccupancyId[];',
    '  legalContinuities: readonly ContinuityId[];',
    '  enabledScope: SubstrateEnabledScope;',
    '}',
    '',
    'export interface PortfolioDef {',
    '  id: PortfolioId;',
    '  displayToken: string;',
    '  continuity: ContinuityId;',
    '  occupancy: OccupancyId;',
    '  legalContinuities: readonly ContinuityId[];',
    '  pinLayer: PinLayerId;',
    '  canChase: boolean;',
    '  blockWalk: boolean;',
    '  defaultContact: string;',
    '  detectionPulse: boolean;',
    '}',
    '',
    'export interface LexemeRewrite {',
    '  portfolio: PortfolioId;',
    '  lexeme: string;',
    '}',
    '',
    'export interface LexemeDef {',
    '  id: string;',
    '  slot: LexemeSlot;',
    '  displayToken: string;',
    '  legalPortfolios: readonly PortfolioId[];',
    '  rewrites: readonly LexemeRewrite[];',
    '}',
    '',
    'export interface UtteranceDef {',
    '  id: string;',
    '  internalLabel: string;',
    '  onScreenMark: string;',
    '  coverage: CoverageId;',
    '  substrate: string;',
    '  portfolio: PortfolioId;',
    '  continuity: ContinuityId;',
    '  occupancy: OccupancyId;',
    '  motion: string;',
    '  sense: string;',
    '  rhythm: string;',
    '  contact: string;',
    '}',
    '',
    'export interface DisplayTokenDef {',
    '  id: string;',
    '  kind: string;',
    '  displayToken: string;',
    '}',
    '',
    "export type StopLossFamily = 'core_strike' | 'scatter_rejoin' | 'unkillable';",
    "export type StopLossCorePolicy = 'exposed' | 'standard' | 'obscured' | 'none';",
    '',
    'export interface StopLossDef {',
    '  id: string;',
    '  continuity: ContinuityId;',
    '  coverage: CoverageId;',
    '  family: StopLossFamily;',
    '  corePolicy: StopLossCorePolicy;',
    '  legalOccupancies: readonly OccupancyId[];',
    '}',
    '',
    'export const SUBSTRATE_DATA: Record<string, SubstrateDef> = {',
  ];

  for (const s of substrates) {
    lines.push(`  ${s.id}: {`);
    lines.push(`    id: '${s.id}',`);
    lines.push(`    displayToken: '${escapeStr(s.displayToken)}',`);
    lines.push(`    residualVerb: '${escapeStr(s.residualVerb)}',`);
    lines.push(`    legalOccupancies: [${s.legalOccupancies.map((v) => `'${v}'`).join(', ')}],`);
    lines.push(`    sortieLegalOccupancies: [${s.sortieLegalOccupancies.map((v) => `'${v}'`).join(', ')}],`);
    lines.push(`    legalContinuities: [${s.legalContinuities.map((v) => `'${v}'`).join(', ')}],`);
    lines.push(`    enabledScope: '${s.enabledScope}',`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('export const PORTFOLIO_DATA: Record<PortfolioId, PortfolioDef> = {');
  for (const p of portfolios) {
    lines.push(`  ${p.id}: {`);
    lines.push(`    id: '${p.id}',`);
    lines.push(`    displayToken: '${escapeStr(p.displayToken)}',`);
    lines.push(`    continuity: '${p.continuity}',`);
    lines.push(`    occupancy: '${p.occupancy}',`);
    lines.push(`    legalContinuities: [${p.legalContinuities.map((v) => `'${v}'`).join(', ')}],`);
    lines.push(`    pinLayer: '${p.pinLayer}',`);
    lines.push(`    canChase: ${p.canChase},`);
    lines.push(`    blockWalk: ${p.blockWalk},`);
    lines.push(`    defaultContact: '${p.defaultContact}',`);
    lines.push(`    detectionPulse: ${p.detectionPulse},`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('export const LEXEME_DATA: Record<string, LexemeDef> = {');
  for (const l of lexemes) {
    const rewrites = l.rewrites
      .map((r) => `{ portfolio: '${r.portfolio}', lexeme: '${r.lexeme}' }`)
      .join(', ');
    lines.push(`  ${l.id}: {`);
    lines.push(`    id: '${l.id}',`);
    lines.push(`    slot: '${l.slot}',`);
    lines.push(`    displayToken: '${escapeStr(l.displayToken)}',`);
    lines.push(`    legalPortfolios: [${l.legalPortfolios.map((v) => `'${v}'`).join(', ')}],`);
    lines.push(`    rewrites: [${rewrites}],`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('export const UTTERANCE_DATA: Record<string, UtteranceDef> = {');
  for (const u of utterances) {
    lines.push(`  ${u.id}: {`);
    lines.push(`    id: '${u.id}',`);
    lines.push(`    internalLabel: '${escapeStr(u.internalLabel)}',`);
    lines.push(`    onScreenMark: '${escapeStr(u.onScreenMark)}',`);
    lines.push(`    coverage: '${u.coverage}',`);
    lines.push(`    substrate: '${u.substrate}',`);
    lines.push(`    portfolio: '${u.portfolio}',`);
    lines.push(`    continuity: '${u.continuity}',`);
    lines.push(`    occupancy: '${u.occupancy}',`);
    lines.push(`    motion: '${u.motion}',`);
    lines.push(`    sense: '${u.sense}',`);
    lines.push(`    rhythm: '${u.rhythm}',`);
    lines.push(`    contact: '${u.contact}',`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('export const DISPLAY_TOKEN_DATA: Record<string, DisplayTokenDef> = {');
  for (const t of displayTokens) {
    lines.push(`  ${t.id}: {`);
    lines.push(`    id: '${t.id}',`);
    lines.push(`    kind: '${t.kind}',`);
    lines.push(`    displayToken: '${escapeStr(t.displayToken)}',`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('export const STOP_LOSS_DATA: Record<string, StopLossDef> = {');
  for (const s of stopLoss) {
    lines.push(`  ${s.id}: {`);
    lines.push(`    id: '${s.id}',`);
    lines.push(`    continuity: '${s.continuity}',`);
    lines.push(`    coverage: '${s.coverage}',`);
    lines.push(`    family: '${s.family}',`);
    lines.push(`    corePolicy: '${s.corePolicy}',`);
    lines.push(`    legalOccupancies: [${s.legalOccupancies.map((v) => `'${v}'`).join(', ')}],`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push(`export const SUBSTRATE_IDS: readonly string[] = [${substrates.map((s) => `'${s.id}'`).join(', ')}];`);
  lines.push(
    `export const SORTIE_SUBSTRATE_IDS: readonly string[] = [${sortieSubstrates.map((s) => `'${s.id}'`).join(', ')}];`,
  );
  lines.push(
    `export const CONCEPTUAL_SUBSTRATE_IDS: readonly string[] = [${CONCEPTUAL_SUBSTRATE_IDS.map((id) => `'${id}'`).join(', ')}];`,
  );
  lines.push("export const PORTFOLIO_IDS: readonly PortfolioId[] = ['jia', 'yi', 'bing', 'ding'];");
  lines.push(`export const LEXEME_IDS: readonly string[] = [${lexemes.map((l) => `'${l.id}'`).join(', ')}];`);
  lines.push(
    `export const UTTERANCE_IDS: readonly string[] = [${utterances.map((u) => `'${u.id}'`).join(', ')}];`,
  );
  lines.push(`export const STOP_LOSS_IDS: readonly string[] = [${stopLoss.map((s) => `'${s.id}'`).join(', ')}];`);
  lines.push('');

  writeFileSync(resolve(OUT_DIR, 'contamination-lexicon-data.ts'), lines.join('\n'), 'utf-8');
  console.log(`  contamination-lexicon-data.ts (${substrates.length} substrates, ${lexemes.length} lexemes, ${stopLoss.length} stop-loss)`);
}

console.log('[codegen] Generating typed data from CSV...');
generateContaminants();
generateUpgrades();
generateRiftFragments();
generateEnemies();
generateContaminationLexicon();
console.log('[codegen] Done.');
