/** Generate production geometry from the exact selected, editable art scene. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {ShapeUtils,Vector2} from 'three';
import {buildOption} from '../../docs/art/demos/purification-forecourt-options/option-a.ts';
import {carveFloor} from '../../docs/art/demos/purification-forecourt-options/shared.ts';
import {RIFT_FOOTPRINT,RIFT_INTERACTION} from '../../docs/art/demos/purification-forecourt-options/rift-a.ts';
import {WALK_SURFACES,LAYOUT_OBSTACLES} from '../../docs/art/demos/purification-last-light/environment.ts';
import {REST_POSITION,REST_YAW,REST_APPROACH,REST_OBJECT_ID} from '../../docs/art/demos/purification-last-light/rest.ts';
import {ACTOR_POSITION} from '../../docs/art/demos/purification-last-light/actor.ts';
import {Model} from '../../docs/art/demos/purification-last-light/model.ts';
import {CAMERA,project} from '../../docs/art/demos/purification-last-light/render.ts';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const option=buildOption(),model=option.model,stations=option.stations;
if(!stations||!option.carved)throw new Error('Selected scene must provide stations and the A breach.');
const nav=new Model();
for(const surface of WALK_SURFACES){
 nav.object=surface.id==='upper'?1:surface.id==='west-ramp'?2:0;
 const faces=ShapeUtils.triangulateShape(surface.points.map(p=>new Vector2(p[0],p[2])),[]);
 for(const [a,b,c]of faces)nav.triangle(surface.points[a],surface.points[c],surface.points[b],'cutstone');
}
carveFloor(nav,option.carved,.25);
carveFloor(nav,RIFT_FOOTPRINT.map(p=>[p[0],p[2]]),.25);
// Read the actual selected bridge deck instead of repeating its authored endpoints.
const bridge=model.triangles.filter(t=>t.object===0&&t.layer==='haven'&&t.normal[1]>.99&&[t.a,t.b,t.c].every(p=>Math.abs(p[1]-.057)<1e-7));
if(bridge.length<2)throw new Error('The selected A bridge deck was not found.');
nav.triangles.push(...bridge);
const round=n=>Math.round(n*1e7)/1e7;
const vector=p=>p.map(round);
const clip=(points,h,above)=>{const out=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],aa=above?a[1]>=h:a[1]<=h,bb=above?b[1]>=h:b[1]<=h;if(aa)out.push(a);if(aa!==bb){const t=(h-a[1])/(b[1]-a[1]);out.push(a.map((n,k)=>n+(b[k]-n)*t));}}return out;};
const local=(p,origin,yaw)=>{const x=p[0]-origin[0],z=p[2]-origin[2];return[x*Math.cos(yaw)-z*Math.sin(yaw),x*Math.sin(yaw)+z*Math.cos(yaw)];};
const rest={id:REST_OBJECT_ID,key:'rest',position:REST_POSITION,yaw:REST_YAW,approach:REST_APPROACH};
const obstacles=[...stations.filter(s=>s.key!=='rift'),rest].map(s=>{
 const ps=model.triangles.filter(t=>t.object===s.id).flatMap(t=>clip(clip([t.a,t.b,t.c],s.position[1]+.12,true),s.position[1]+.65,false)).map(p=>local(p,s.position,s.yaw));
 if(!ps.length)throw new Error(`Missing ${s.key} physical base`);
 return{id:s.key,position:s.position,yaw:s.yaw,kind:'box',bounds:[Math.min(...ps.map(p=>p[0])),Math.min(...ps.map(p=>p[1])),Math.max(...ps.map(p=>p[0])),Math.max(...ps.map(p=>p[1]))],height:.65};
});
for(const o of LAYOUT_OBSTACLES)obstacles.push({id:o.id,position:o.position,yaw:o.kind==='box'?o.yaw:0,kind:o.kind,bounds:o.kind==='box'?[-o.half[0],-o.half[1],o.half[0],o.half[1]]:[-o.radius,-o.radius,o.radius,o.radius],height:.65});
const deviceData=stations.map(s=>{
 const tris=model.triangles.filter(t=>t.object===s.id),ps=tris.flatMap(t=>[t.a,t.b,t.c]),screen=ps.map(p=>project(p));
 const base=project(s.position);return{...s,...(s.key==='rift'?{interaction:RIFT_INTERACTION}:{}),floor:s.position[1]>1?'upper':'main',screen:base,approachScreen:project(s.approach),visualBounds:[Math.min(...screen.map(p=>p[0]))-base[0],Math.min(...screen.map(p=>p[1]))-base[1],Math.max(...screen.map(p=>p[0]))-base[0],Math.max(...screen.map(p=>p[1]))-base[1]],height:Math.max(...ps.map(p=>p[1]))-s.position[1]};
});
// Exact opaque authored surfaces. A compact binary literal avoids enormous TS
// tuple types; a BVH is compiled once by the runtime, never once per observation.
const opaque=model.triangles.filter(t=>t.layer==='haven'&&t.object!==7&& !['glass','liquid','energy','pollutant','ember','lamp'].includes(t.material)&&Math.max(t.a[1],t.b[1],t.c[1])>.14);
const packed=new Float32Array(opaque.length*10);
opaque.forEach((t,i)=>packed.set([...t.a,...t.b,...t.c,t.object],i*10));
const data={camera:CAMERA,spawn:ACTOR_POSITION,footRadius:.22,breach:option.carved,riftCut:RIFT_FOOTPRINT.map(p=>[p[0],p[2]]),walk:nav.triangles.map(t=>({route:t.object===1?'upper':t.object===2?'west-ramp':'main',points:[vector(t.a),vector(t.b),vector(t.c)]})),obstacles,stations:deviceData,rest};
const output=`/** Generated by tools/last-light/export-layout.mjs from the selected A scene. Do not edit. */\nexport const LAST_LIGHT_DATA = ${JSON.stringify(data,null,2)};\nexport const LAST_LIGHT_OCCLUSION_BASE64 = '${Buffer.from(packed.buffer).toString('base64')}';\n`;
const target=path.join(root,'src/generated/last-light-layout.ts');
if(process.argv.includes('--check')){if(await fs.readFile(target,'utf8')!==output)throw new Error('Last Light layout data is stale');}
else await fs.writeFile(target,output);
console.log(JSON.stringify({walkTriangles:data.walk.length,bridgeTriangles:bridge.length,obstacles:obstacles.length,occluderTriangles:opaque.length,stations:stations.length,target}));
